config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: [:show]
  resources :subs
  resources :users, except: [:show, :new, :index] do
    member do
      get 'password_edit'
    end
  end
  resources :links do
    member do
      get 'click'
    end
    resources :votes, only: [:create, :destroy]
    resources :comments, except: [:index]
  end

  root 'links#index'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy', as: :logout

  get '/signup' => 'users#new', as: :signup

  get '/:name' => 'subs#show', as: :sub_name

  get '/users/:username' => 'users#show', as: :user_name

end

app/models/cleansed_string.rb
class CleansedString

  attr_accessor :name

  def initialize(name)
    self.name = name
    cleanse
  end

  def cleanse
    name_to_s
    downcase_name
    remove_spaces
    sanitize
  end

  def name_to_s
    self.name = name.to_s
  end

  def downcase_name
    name.downcase!
  end

  def remove_spaces
    name.gsub!(/\s/, "_")
  end

  def sanitize
    self.name = URI.escape(name, "!?&")
  end

  def to_s
    name
  end

end

app/models/click.rb
class Click < KarmaContributor
  belongs_to :link
  belongs_to :user

  after_save :update_karma

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates :content, :user, :link, presence: true
end

app/models/karma_contributor.rb
class KarmaContributor < ActiveRecord::Base
  self.abstract_class = true

  def update_karma
    vote_score = Vote.where(:link_id => self.link_id).sum(:value)
    click_score = Click.where(:link_id => self.link_id).sum(:value)
    karma_score = (vote_score + click_score) / 5
    self.link.update!(karma: karma_score)
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  paginates_per 10

  belongs_to :sub
  belongs_to :user
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  before_validation :url_has_proper_prefix
  validates :title, :url, :summary, :user, :sub, presence: true
  validates :url, uniqueness: { case_sensitive: false }
  validates :url, :format => { with: /\Ahttps?:\/\//}

  after_update :update_user_karma

  def update_user_karma
    karma_score = Link.where(:user_id => self.user_id).sum(:karma)
    self.user.update!(karma: karma_score)
  end

  def url_has_proper_prefix
    unless self.url =~ /\Ahttps?:\/\//
      self.url = "http://" + url
    end
  end

  def tag_list
    tags.map { |tag| tag.name }.join(", ")
  end

  def tag_list=(str)
    tag_names = str.split(",").map(&:strip)
    tags = tag_names.map do |name|
      Tag.find_or_initialize_by(name: CleansedString.new(name).to_s)
    end
    self.tags = tags
  end

end

app/models/route_recognizer.rb
class RouteRecognizer
  attr_reader :paths

  # To use this inside your app, call:
  # `RouteRecognizer.new.initial_path_segments`
  # This returns an array, e.g.: ['assets','blog','team','faq','users']
  # Credit to bantic/rails_route_recognizer.rb

  INITIAL_SEGMENT_REGEX = %r{^\/([^\/\(:]+)}

  def initialize
    routes = Rails.application.routes.routes
    @paths = routes.collect {|r| r.path.spec.to_s }
  end

  def initial_path_segments
    @initial_path_segments ||= begin
      paths.collect {|path| match_initial_path_segment(path)}.compact.uniq
    end
  end

  def match_initial_path_segment(path)
    if match = INITIAL_SEGMENT_REGEX.match(path)
      match[1]
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  paginates_per 10
  has_many :links
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validate :name_not_a_resource
  before_save :downcase_name

  def name_not_a_resource
    resource_names = RouteRecognizer.new.initial_path_segments
    errors.add(:name, "sub-breddit name not available") if resource_names.include? name
  end

  def downcase_name
    self.name.downcase!
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :links, through: :taggings
  before_validation :cleanse_input

  validates :name, presence: true, uniqueness: true

  def to_param
    name
  end

  def cleanse_input
    self.name = CleansedString.new(name).to_s
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10
  has_many :links
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :voted_links, :through => :votes, :source => 'link'
  has_many :clicked_links, :through => :clicks, :source => 'link'
  has_many :commented_links, :through => :comments, :source => 'link'
  has_secure_password
  validates :username, :name, :email, :bio, presence: true
  validates :username, uniqueness: true
  validates :username, format: { without: /\s/ }

end

app/models/vote.rb
class Vote < KarmaContributor
  belongs_to :link
  belongs_to :user

  validates :user, :link, presence: true

  after_save :update_karma

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all.page(params[:page])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      flash[:success] = "Sub-breddit created!"
      redirect_to subs_path
    else
      render :new
    end
  end

  def show
    @sub = params[:id] ? Sub.find(params[:id]) : Sub.find_by(name: params[:name])
    if @sub.nil?
      flash[:danger] = "Not a valid sub-breddit name"
      redirect_to root_path    
    else
      @links = @sub.links.order(karma: :desc).page(params[:page])
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:name, :description)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(name: params[:id])
    @links = @tag.links.order(karma: :desc).page(params[:page])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :disallow_user, only: [:new, :create]
  before_action :require_user, only: [:update, :edit, :password_edit]

  def index
    @users = User.order(karma: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created!"
      redirect_to user_name_path(@user.username)
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(username: params[:username])
    unless @user.nil?
      @submitted_links = @user.links.order(karma: :desc).page(params[:page]).per(5)
      @voted_links = @user.voted_links.order(created_at: :desc).page(params[:page]).per(5)
      @clicked_links = @user.clicked_links.order(created_at: :desc).page(params[:page]).per(5)
    else
      flash[:danger] = "Not a valid user"
      redirect_to users_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:old_password] && @user.authenticate(params[:user][:old_password])
      @user.update(password: params[:user][:password])
      flash[:success] = "Password successfully updated"
      redirect_to user_name_path(@user.username)
    else
      if @user.update_attributes(user_params)
        flash[:success] = "Profile successfully updated"
        redirect_to user_name_path(@user.username)
      else
        render :edit
      end
    end
  end

  def password_edit
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:username, :name, :email, :bio, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/users/_user.html.erb
<div class="col-xs-12 index">
  <%= link_to user.name.upcase, user_name_path(user.username) %>
  <p>Karma: <%= user.karma %></p>
  <p>User Since: <%= user.created_at.strftime("%D") %></p>
</div>

app/views/users/edit.html.erb
<h1>EDIT USER</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :bio %>
  <%= f.button :submit %>
<% end %>

<div class="btn btn-default links">
  <%= link_to "Back to Users", users_path %>
</div>
<div class="btn btn-primary links">
  <%= link_to "Change Password", password_edit_user_path, id: "edit-profile" %>
</div>

app/views/users/index.html.erb
<h1>ALL USERS</h1>

<%= render @users %>

<div class="paginate">
  <%= paginate @users %>
</div>

<div class="btn btn-default links">
  <%= link_to "Create a New User", signup_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>

app/views/users/new.html.erb
<h1>CREATE NEW USER</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :bio %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

<div class="btn btn-default links">
  <%= link_to "Back to Users", users_path %>
</div>

app/views/users/password_edit.html.erb
<h1>SET NEW PASSWORD FOR <%= @user.username.upcase %></h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :old_password %>
  <%= f.button :submit %>
<% end %>

<div class="btn btn-default links">
  <%= link_to "Back to Users", users_path %>
</div>

app/views/users/show.html.erb
<div class="col-sm-3 link aside">
  <h2><%= @user.name.upcase %></h2>
  <h4>Username:</h4>
  <p><%= @user.username %></p>
  <h4>Total Karma:</h4>
  <p><%= @user.karma %></p>
  <h4>Date Created</h4>
  <p><%= @user.created_at.strftime("%A, %b %d %Y at %-I:%M %p") %></p>
  <h4>User Bio</h4>
  <p><%= simple_format(@user.bio).html_safe %></p>
</div>
<div class="col-sm-9 link">
  <h2>SUBMITTED LINKS</h2>
  <%= render partial: 'links/link', collection: @submitted_links %>
  <div class="paginate">
    <%= paginate @submitted_links %>
  </div>
  <h2>VOTED LINKS</h2>
  <%= render partial: 'links/link', collection: @voted_links %>
  <div class="paginate">
    <%= paginate @voted_links %>
  </div>
  <h2>CLICKED LINKS</h2>
  <%= render partial: 'links/link', collection: @clicked_links %>
  <div class="paginate">
    <%= paginate @clicked_links %>
  </div>
</div>

<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Back to Users", users_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Submit New Link", new_link_path %>
</div>
<% if current_user && current_user = @user %>
  <div class="btn btn-primary links">
    <%= link_to "Edit My Profile", edit_user_path(@user), id: "edit-profile" %>
  </div>
<% end %>