config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: [:show]
  resources :subs
  resources :users, except: [:show, :new, :index] do
    member do
      get 'password_edit'
    end
  end
  resources :links do
    member do
      get 'click'
    end
    resources :votes, only: [:create, :destroy]
    resources :comments, except: [:index]
  end

  root 'links#index'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy', as: :logout

  get '/signup' => 'users#new', as: :signup

  get '/:name' => 'subs#show', as: :sub_name

  get '/users/:username' => 'users#show', as: :user_name

end

app/models/cleansed_string.rb
class CleansedString

  attr_accessor :name

  def initialize(name)
    self.name = name
    cleanse
  end

  def cleanse
    name_to_s
    downcase_name
    remove_spaces
    sanitize
  end

  def name_to_s
    self.name = name.to_s
  end

  def downcase_name
    name.downcase!
  end

  def remove_spaces
    name.gsub!(/\s/, "_")
  end

  def sanitize
    self.name = URI.escape(name, "!?&")
  end

  def to_s
    name
  end

end

app/models/click.rb
class Click < KarmaContributor
  belongs_to :link
  belongs_to :user

  after_save :update_karma

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates :content, :user, :link, presence: true
end

app/models/karma_contributor.rb
class KarmaContributor < ActiveRecord::Base
  self.abstract_class = true

  def update_karma
    vote_score = Vote.where(:link_id => self.link_id).sum(:value)
    click_score = Click.where(:link_id => self.link_id).sum(:value)
    karma_score = (vote_score + click_score) / 5
    self.link.update!(karma: karma_score)
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  paginates_per 10

  belongs_to :sub
  belongs_to :user
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  before_validation :url_has_proper_prefix
  validates :title, :url, :summary, :user, :sub, presence: true
  validates :url, uniqueness: { case_sensitive: false }
  validates :url, :format => { with: /\Ahttps?:\/\//}

  after_update :update_user_karma

  def update_user_karma
    karma_score = Link.where(:user_id => self.user_id).sum(:karma)
    self.user.update!(karma: karma_score)
  end

  def url_has_proper_prefix
    unless self.url =~ /\Ahttps?:\/\//
      self.url = "http://" + url
    end
  end

  def tag_list
    tags.map { |tag| tag.name }.join(", ")
  end

  def tag_list=(str)
    tag_names = str.split(",").map(&:strip)
    tags = tag_names.map do |name|
      Tag.find_or_initialize_by(name: CleansedString.new(name).to_s)
    end
    self.tags = tags
  end

end

app/models/route_recognizer.rb
class RouteRecognizer
  attr_reader :paths

  # To use this inside your app, call:
  # `RouteRecognizer.new.initial_path_segments`
  # This returns an array, e.g.: ['assets','blog','team','faq','users']
  # Credit to bantic/rails_route_recognizer.rb

  INITIAL_SEGMENT_REGEX = %r{^\/([^\/\(:]+)}

  def initialize
    routes = Rails.application.routes.routes
    @paths = routes.collect {|r| r.path.spec.to_s }
  end

  def initial_path_segments
    @initial_path_segments ||= begin
      paths.collect {|path| match_initial_path_segment(path)}.compact.uniq
    end
  end

  def match_initial_path_segment(path)
    if match = INITIAL_SEGMENT_REGEX.match(path)
      match[1]
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  paginates_per 10
  has_many :links
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validate :name_not_a_resource
  before_save :downcase_name

  def name_not_a_resource
    resource_names = RouteRecognizer.new.initial_path_segments
    errors.add(:name, "sub-breddit name not available") if resource_names.include? name
  end

  def downcase_name
    self.name.downcase!
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :links, through: :taggings
  before_validation :cleanse_input

  validates :name, presence: true, uniqueness: true

  def to_param
    name
  end

  def cleanse_input
    self.name = CleansedString.new(name).to_s
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10
  has_many :links
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :voted_links, :through => :votes, :source => 'link'
  has_many :clicked_links, :through => :clicks, :source => 'link'
  has_many :commented_links, :through => :comments, :source => 'link'
  has_secure_password
  validates :username, :name, :email, :bio, presence: true
  validates :username, uniqueness: true
  validates :username, format: { without: /\s/ }

end

app/models/vote.rb
class Vote < KarmaContributor
  belongs_to :link
  belongs_to :user

  validates :user, :link, presence: true

  after_save :update_karma

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def index
    @links = Link.order(karma: :desc).page(params[:page])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.user = current_user
    if @link.save
      flash[:success] = "Link successfully created!"
      redirect_to :root
    else
      if @link.errors[:url] && !@link.url.nil?
        vote_link = Link.find_by("url = ?", @link.url)
        vote_link.votes.create(value: 5, user_id: current_user.id)
        flash[:info] = "Link to that URL already exists"
        redirect_to root_path
      else
        render :new
      end
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(link_params)
      flash[:success] = "Link updated!"
      redirect_to @link
    else
      render :edit
    end
  end

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
  end

  def click
    @link = Link.find(params[:id])
    @link.clicks.create(value: 1, user: current_user)
    redirect_to @link.url
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :summary, :sub_id, :tag_list)
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all.page(params[:page])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      flash[:success] = "Sub-breddit created!"
      redirect_to subs_path
    else
      render :new
    end
  end

  def show
    @sub = params[:id] ? Sub.find(params[:id]) : Sub.find_by(name: params[:name])
    if @sub.nil?
      flash[:danger] = "Not a valid sub-breddit name"
      redirect_to root_path    
    else
      @links = @sub.links.order(karma: :desc).page(params[:page])
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:name, :description)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(name: params[:id])
    @links = @tag.links.order(karma: :desc).page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/links/_form.html.erb
<%= simple_form_for @link do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.input :summary %>
  <%= f.input :tag_list %>
  <%= f.association :sub %>
  <%= f.button :submit %>
<% end %>

app/views/links/_link.html.erb
<div class="col-xs-1 votes text-center">
  <%= render partial: 'links/vote_links', locals: { link: link } %>
</div>
<div class="col-xs-11 link">
  <%= link_to link.title, click_link_path(link) %>
  <p>
    <span class="dark">submitted to sub:</span>
    <%= link_to link.sub.name, sub_name_path(link.sub.name) %>
    <span class="dark">by: </span>
    <%= link_to link.user.name, user_name_path(link.user.username) %>
    <span class="dark">on: </span>
    <%= link.created_at.strftime("%A, %b %d %Y at %-I:%M %p") %>&nbsp&nbsp&nbsp
    <ul class="list-inline">
      <li><%= link_to "Comments", link %></li>
      <li>Tags:</li>
      <%= render link.tags %>
    </ul>
  </p>
  <p><%= link.summary %></p>
</div>

app/views/links/_vote_links.html.erb
<% if current_user %>
  <%= link_to link_votes_path(link, :value => 5), :method => :post do %>
    <i id="upvote" class="glyphicon glyphicon-triangle-top"></i>
  <% end %>
  <p><span class="dark"><%= link.karma %></span></p>
  <%= link_to link_votes_path(link, :value => -5), :method => :post do %>
    <i id="downvote" class="glyphicon glyphicon-triangle-bottom"></i>
  <% end %>
<% else %>
  <p id="link-karma"><span class="dark"><%= link.karma %></span></p>
<% end %>

app/views/links/edit.html.erb
<h1>EDIT LINK</h1>

<%= render partial: 'form' %>

<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>

app/views/links/index.html.erb
<h1>ALL LINKS</h1>

<%= render @links %>

<div class="paginate">
  <%= paginate @links %>
</div>

<% if current_user %>
  <div class="btn btn-default links">
    <%= link_to "Submit a New Link", new_link_path %>
  </div>
<% end %>
<div class="btn btn-default links">
  <%= link_to "All Sub-Breddits", subs_path %>
</div>

app/views/links/new.html.erb
<h1>CREATE NEW LINK</h1>

<%= simple_form_for @link do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.input :summary %>
  <%= f.association :sub %>
  <%= f.button :submit %>
<% end %>

<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>

app/views/links/show.html.erb
<div class="col-sm-4">
  <%= render partial: 'subs/sub_info', locals: { :@sub => @link.sub } %>
</div>

<div class="col-sm-8">
  <div class="link-single">
    <%= render @link %>
  </div>

  <div class="comment">
    <h3>Comments</h3>
    <%= render template: 'comments/new' if current_user%>
    <%= render @link.comments %>
  </div>
</div>

app/views/subs/_sub.html.erb
<div class="col-xs-12 index">
  <%= link_to sub.name.upcase, sub %>
  <p>Created on: <%= sub.created_at.strftime("%A, %b %d %Y at %-I:%M %p") %></p>
</div>

app/views/subs/_sub_info.html.erb
<h2><%= @sub.name.upcase %></h2>
<h4>Date Created</h4>
<p><%= @sub.created_at.strftime("%A, %b %d %Y at %-I:%M %p") %></p>
<h4>Sub-Breddit Description</h4>
<p><%= @sub.description %></p>

app/views/subs/index.html.erb
<h1>ALL SUB-BREDDITS</h1>

<%= render @subs %>

<div class="paginate">
  <%= paginate @subs %>
</div>

<div class="btn btn-default links">
  <%= link_to "Create a New Sub-Breddit", new_sub_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>

app/views/subs/new.html.erb
<h1>CREATE NEW SUB-BREDDIT</h1>

<%= simple_form_for @sub do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Back to Sub-Breddits", subs_path %>
</div>

app/views/subs/show.html.erb
<div class="col-sm-3 link aside">
  <%= render partial: 'sub_info' %>
</div>
<div class="col-sm-9 link">
  <h2>LINKS</h2>
  <%= render partial: 'links/link', collection: @links %>
</div>

<div class="btn btn-default links">
  <%= link_to "Back to Home", root_path %>
</div>
<div class="btn btn-default links">
  <%= link_to "Back to Sub-Breddits", subs_path %>
</div>

app/views/tags/_tag.html.erb
<li><%= link_to tag.name, tag %></li>

app/views/tags/show.html.erb
<h2>LINKS FOR TAG: <%= @tag.name.upcase %></h2>

<%= render @links %>

<div class="paginate">
  <%= paginate @links %>
</div>

<% if current_user %>
  <div class="btn btn-default links">
    <%= link_to "Submit a New Link", new_link_path %>
  </div>
<% end %>
<div class="btn btn-default links">
  <%= link_to "All Sub-Breddits", subs_path %>
</div>