config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: [:show]
  resources :subs
  resources :users, except: [:show, :new, :index] do
    member do
      get 'password_edit'
    end
  end
  resources :links do
    member do
      get 'click'
    end
    resources :votes, only: [:create, :destroy]
    resources :comments, except: [:index]
  end

  root 'links#index'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_create
  delete '/logout' => 'sessions#destroy', as: :logout

  get '/signup' => 'users#new', as: :signup

  get '/:name' => 'subs#show', as: :sub_name

  get '/users/:username' => 'users#show', as: :user_name

end

app/models/cleansed_string.rb
class CleansedString

  attr_accessor :name

  def initialize(name)
    self.name = name
    cleanse
  end

  def cleanse
    name_to_s
    downcase_name
    remove_spaces
    sanitize
  end

  def name_to_s
    self.name = name.to_s
  end

  def downcase_name
    name.downcase!
  end

  def remove_spaces
    name.gsub!(/\s/, "_")
  end

  def sanitize
    self.name = URI.escape(name, "!?&")
  end

  def to_s
    name
  end

end

app/models/click.rb
class Click < KarmaContributor
  belongs_to :link
  belongs_to :user

  after_save :update_karma

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates :content, :user, :link, presence: true
end

app/models/karma_contributor.rb
class KarmaContributor < ActiveRecord::Base
  self.abstract_class = true

  def update_karma
    vote_score = Vote.where(:link_id => self.link_id).sum(:value)
    click_score = Click.where(:link_id => self.link_id).sum(:value)
    karma_score = (vote_score + click_score) / 5
    self.link.update!(karma: karma_score)
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  paginates_per 10

  belongs_to :sub
  belongs_to :user
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  before_validation :url_has_proper_prefix
  validates :title, :url, :summary, :user, :sub, presence: true
  validates :url, uniqueness: { case_sensitive: false }
  validates :url, :format => { with: /\Ahttps?:\/\//}

  after_update :update_user_karma

  def update_user_karma
    karma_score = Link.where(:user_id => self.user_id).sum(:karma)
    self.user.update!(karma: karma_score)
  end

  def url_has_proper_prefix
    unless self.url =~ /\Ahttps?:\/\//
      self.url = "http://" + url
    end
  end

  def tag_list
    tags.map { |tag| tag.name }.join(", ")
  end

  def tag_list=(str)
    tag_names = str.split(",").map(&:strip)
    tags = tag_names.map do |name|
      Tag.find_or_initialize_by(name: CleansedString.new(name).to_s)
    end
    self.tags = tags
  end

end

app/models/route_recognizer.rb
class RouteRecognizer
  attr_reader :paths

  # To use this inside your app, call:
  # `RouteRecognizer.new.initial_path_segments`
  # This returns an array, e.g.: ['assets','blog','team','faq','users']
  # Credit to bantic/rails_route_recognizer.rb

  INITIAL_SEGMENT_REGEX = %r{^\/([^\/\(:]+)}

  def initialize
    routes = Rails.application.routes.routes
    @paths = routes.collect {|r| r.path.spec.to_s }
  end

  def initial_path_segments
    @initial_path_segments ||= begin
      paths.collect {|path| match_initial_path_segment(path)}.compact.uniq
    end
  end

  def match_initial_path_segment(path)
    if match = INITIAL_SEGMENT_REGEX.match(path)
      match[1]
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  paginates_per 10
  has_many :links
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validate :name_not_a_resource
  before_save :downcase_name

  def name_not_a_resource
    resource_names = RouteRecognizer.new.initial_path_segments
    errors.add(:name, "sub-breddit name not available") if resource_names.include? name
  end

  def downcase_name
    self.name.downcase!
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :links, through: :taggings
  before_validation :cleanse_input

  validates :name, presence: true, uniqueness: true

  def to_param
    name
  end

  def cleanse_input
    self.name = CleansedString.new(name).to_s
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10
  has_many :links
  has_many :votes
  has_many :clicks
  has_many :comments
  has_many :voted_links, :through => :votes, :source => 'link'
  has_many :clicked_links, :through => :clicks, :source => 'link'
  has_many :commented_links, :through => :comments, :source => 'link'
  has_secure_password
  validates :username, :name, :email, :bio, presence: true
  validates :username, uniqueness: true
  validates :username, format: { without: /\s/ }

end

app/models/vote.rb
class Vote < KarmaContributor
  belongs_to :link
  belongs_to :user

  validates :user, :link, presence: true

  after_save :update_karma

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="jumbotron">
    <%= render partial: "shared/user_links" %>
    <div class="container">
      <div class="text-center">
        <h1>BREDDIT</h1>
        <h2>The Freshest Bread-Related Links</h2>
      </div>
    </div>
    <ul class="root-links links">
      <li><%= link_to "All Links", root_path %></li>
      <li><%= link_to "Sub-Breddits", subs_path %></li>
      <% if current_user %>
        <li><%= link_to "My Profile", user_name_path(current_user.username) %></li>
      <% end %>
    </ul>
  </div>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="row main">
      <%= yield %>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          The Ironyard Copyright 2013. All Rights Reserved
        </div>
        <div class="col-xs-6">
          <nav>
            <ul class="list-inline text-right">
              <li><a href="#">Bread</a></li>
              <li><a href="#">Tastes</a></li>
              <li><a href="#">So</a></li>
              <li><a href="#">Good</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/shared/_user_links.html.erb
<% if current_user %>
  <ul class="user-login links">
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li><%= link_to "Log Out", logout_path, method: :delete %></li>
  </ul>
<% else %>
  <ul class="user-login links">
    <li><%= link_to "Log In", login_path %></li>
    <li><%= link_to "New User", signup_path %></li>
  </ul>
<% end %>